/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";
import { Namespace } from "./Namespace";
import { Pagination } from "./Pagination";

export const NamespaceListResponse: core.serialization.ObjectSchema<
    serializers.NamespaceListResponse.Raw,
    Rivet.NamespaceListResponse
> = core.serialization.object({
    namespaces: core.serialization.list(Namespace),
    pagination: Pagination,
});

export declare namespace NamespaceListResponse {
    export interface Raw {
        namespaces: Namespace.Raw[];
        pagination: Pagination.Raw;
    }
}
