// This file was auto-generated by Fern from our API Definition.

package api

type RunnersListRequest struct {
	Namespace      string  `json:"-"`
	Name           *string `json:"-"`
	RunnerIds      *string `json:"-"`
	IncludeStopped *bool   `json:"-"`
	Limit          *int    `json:"-"`
	Cursor         *string `json:"-"`
}

type RunnersListNamesRequest struct {
	Namespace string  `json:"-"`
	Limit     *int    `json:"-"`
	Cursor    *string `json:"-"`
}
