/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         namespace: "namespace"
 *     }
 */
export interface RunnersListRequest {
    namespace: string;
    name?: string;
    runnerIds?: string;
    includeStopped?: boolean;
    limit?: number;
    cursor?: string;
}
