/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespaceListResponse {
    #[serde(rename = "namespaces")]
    pub namespaces: Vec<models::Namespace>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl NamespaceListResponse {
    pub fn new(namespaces: Vec<models::Namespace>, pagination: models::Pagination) -> NamespaceListResponse {
        NamespaceListResponse {
            namespaces,
            pagination: Box::new(pagination),
        }
    }
}

